class Syntax():
    #
    BPUSH   = 'bpush'
    SPUSH   = 'spush'
    IPUSH   = 'ipush'
    FPUSH   = 'fpush'
    DPUSH   = 'dpush'
    SWAP    = 'swap'
    SWAP2   = 'swap2'
    DUP     = 'dup'
    DUP2    = 'dup2'

    # loading and storing variables
    BSTORE  = 'bstore'
    SSTORE  = 'sstore'
    ISTORE  = 'istore'
    FSTORE  = 'fstore'
    DSTORE  = 'dstore'
    BLOAD   = 'bload'
    SLOAD   = 'sload'
    ILOAD   = 'iload'
    FLOAD   = 'fload'
    DLOAD   = 'dload'

    # arithmetic and bitwise operations
    BADD    = 'badd'
    BSUB    = 'bsub'
    BMUL    = 'bmul'
    BDIV    = 'bdiv'
    BMOD    = 'bmod'
    BNOT    = 'bnot'
    BAND    = 'band'
    BOR     = 'bor'
    BXOR    = 'bxor'
    SADD    = 'sadd'
    SSUB    = 'ssub'
    SMUL    = 'smul'
    SDIV    = 'sdiv'
    SMOD    = 'smod'
    SNOT    = 'snot'
    SAND    = 'sand'
    SOR     = 'sor'
    SXOR    = 'sxor'
    IADD    = 'iadd'
    ISUB    = 'isub'
    IMUL    = 'imul'
    IDIV    = 'idiv'
    IMOD    = 'imod'
    INOT    = 'inot'
    IAND    = 'iand'
    IOR     = 'ior'
    IXOR    = 'ixor'
    FADD    = 'fadd'
    FSUB    = 'fsub'
    FMUL    = 'fmul'
    FDIV    = 'fdiv'
    FMOD    = 'fmod'
    FNOT    = 'fnot'
    FAND    = 'fand'
    FOR     = 'for'
    FXOR    = 'fxor'
    DADD    = 'dadd'
    DSUB    = 'dsub'
    DMUL    = 'dmul'
    DDIV    = 'ddiv'
    DMOD    = 'dmod'
    DNOT    = 'dnot'
    DAND    = 'dand'
    DOR     = 'dor'
    DXOR    = 'dxor'

    # comparators
    #

    # logic and control flow
    GOTO    = 'goto'
    LABEL   = 'label'
    JUMP    = 'jump'
    IFE    = 'ifequal'
    IFN    = 'ifnot'
    IFNE   = 'ifnotequal'
    IFLT   = 'iflessthan'
    IFLE   = 'iflessequal'
    IFGT   = 'ifgreaterthan'
    IFGE   = 'ifgreaterequal'

    # method invokation
    DEFINE  = 'define'
    INVOKE  = 'invoke'
    RETURN  = 'return'
    BRETURN = 'breturn'
    SRETURN = 'sreturn'
    IRETURN = 'ireturn'
    FRETURN = 'freturn'

    # type conversion
    #

    # system calls
    BPRINT  = 'bprint'
    SPRINT  = 'sprint'
    IPRINT  = 'iprint'
    FPRINT  = 'fprint'
    DPRINT  = 'dprint'
    APRINT  = 'aprint'
    BPROMPT = 'bprompt'
    SPROMPT = 'sprompt'
    IPROMPT = 'iprompt'
    FPROMPT = 'fprompt'
    DPROMPT = 'dprompt'
    APROMPT = 'aprompt'

    # data types
    VOID    = 'void'
    BOOL    = 'bool'
    BYTE    = 'byte'
    SHORT   = 'short'
    INT     = 'int'
    FLOAT   = 'float'
    DOUBLE  = 'double'
    ADDRESS = 'address'

    # other
    COMMENT = '#'
    PASS    = 'pass'
